steps:
  patch:
    image: alpine:latest
    commands:
      - apk add --no-cache git quilt
      - git clone https://codeberg.org/woodpecker-plugins/docker-buildx.git
      - quilt push -a
      - echo -n latest, > .tags
      - git -C docker-buildx describe --tags --match="v*" --abbrev=0 >> .tags
  build-and-push:
    image: woodpeckerci/plugin-docker-buildx:latest
    settings:
      repo: ${CI_REPO_OWNER%%io}/plugin-docker-buildx
      platforms: linux/amd64,linux/arm64
      context: docker-buildx
      dockerfile: docker-buildx/Dockerfile
      username:
        from_secret: docker_username
      password:
        from_secret: docker_password
      ssh_key:
        from_secret: ssh_key
when:
  - event: [push, manual, cron]
    branch: [master, main]
