steps:
  patch:
    image: alpine:latest
    commands:
      - apk add --no-cache git quilt
      - git clone https://codeberg.org/woodpecker-plugins/docker-buildx.git
      - quilt push -a
  build-and-push:
    image: woodpeckerci/plugin-docker-buildx:6.0.2
    settings:
      repo: "milanmeu/frontend-server-collection"
      tags: latest
      platforms: linux/amd64,linux/arm64
      dockerfile: docker-buildx/Dockerfile
      username:
        from_secret: docker_username
      password:
        from_secret: docker_password
      ssh_key:
        from_secret: ssh_key
      dry_run: true
when:
  - event: [push, manual]
    branch: [master, main]
