steps:
  patch:
    image: alpine:latest
    commands:
      - apk add --no-cache git quilt
      - git clone https://codeberg.org/woodpecker-plugins/docker-buildx.git
      - quilt push -a
      - PLUGIN_VERSION=$(git describe --tags --match="v*" --abbrev=0)
      - export PLUGIN_VERSION
  build-and-push:
    image: woodpeckerci/plugin-docker-buildx:latest
    settings:
      repo: milanmeu/redpencil-docker-buildx
      tags: ${PLUGIN_VERSION},latest
      platforms: linux/amd64,linux/arm64
      context: docker-buildx
      dockerfile: docker-buildx/Dockerfile
      username:
        from_secret: docker_username
      password:
        from_secret: docker_password
      ssh_key:
        from_secret: ssh_key
when:
  - event: [push, manual, cron]
    branch: [master, main]
